<a href="https://colab.research.google.com/github/Alexis0104343/Analisis_de_datos_2026/blob/main/A_D_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import yfinance as yt
df_az=yt.download("AMZN",start= "2024-01-01", end="2026-01-01")
df_az.head()
df_az

/tmp/ipython-input-2780908362.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_az=yt.download("AMZN",start= "2024-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2024-01-02  149.929993  152.380005  148.389999  151.539993  47339400
2024-01-03  148.470001  151.050003  148.330002  149.199997  49425500
2024-01-04  144.570007  147.380005  144.050003  145.589996  56039800
2024-01-05  145.240005  146.589996  144.529999  144.690002  45153100
2024-01-08  149.100006  149.399994  146.149994  146.740005  46757100
...                ...         ...         ...         ...       ...
2025-12-24  232.380005  232.949997  231.330002  232.130005  11420500
2025-12-26  232.520004  232.990005  231.179993  232.039993  15994700
2025-12-29  232.070007  232.600006  230.770004  231.940002  19797900
2025-12-30  232.529999  232.770004  230.199997  231.210007  21910500
2025-12-31  230.820007  232.990005  230.119995  232.910004  24383700

[502 rows x 5 columns]

In [ ]:
df_az.to_csv("/content/drive/MyDrive/Data/finanzas_amazon.csv")

In [ ]:
import pandas as pd

In [ ]:
df_az=pd.read_csv("/content/drive/MyDrive/Data/finanzas_amazon.csv")
df_az.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,AMZN,AMZN,AMZN,AMZN,AMZN
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,149.92999267578125,152.3800048828125,148.38999938964844,151.5399932861328,47339400
3,2024-01-03,148.47000122070312,151.0500030517578,148.3300018310547,149.1999969482422,49425500
4,2024-01-04,144.57000732421875,147.3800048828125,144.0500030517578,145.58999633789062,56039800

In [ ]:
df_az.colums=["Date","Close","High","Low","Open","Volume"]
df_az.head()

/tmp/ipython-input-1451125492.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_az.colums=["Date","Close","High","Low","Open","Volume"]

,Price,Close,High,Low,Open,Volume
0,Ticker,AMZN,AMZN,AMZN,AMZN,AMZN
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,149.92999267578125,152.3800048828125,148.38999938964844,151.5399932861328,47339400
3,2024-01-03,148.47000122070312,151.0500030517578,148.3300018310547,149.1999969482422,49425500
4,2024-01-04,144.57000732421875,147.3800048828125,144.0500030517578,145.58999633789062,56039800

In [ ]:
df_az=df_az.iloc[2:,:].reset_index(drop=True)

In [ ]:
df_az.head()

,Date,Close,High,Low,Open,Volume
0,2024-01-02,149.92999267578125,152.3800048828125,148.38999938964844,151.5399932861328,47339400
1,2024-01-03,148.47000122070312,151.0500030517578,148.3300018310547,149.1999969482422,49425500
2,2024-01-04,144.57000732421875,147.3800048828125,144.0500030517578,145.58999633789062,56039800
3,2024-01-05,145.24000549316406,146.58999633789062,144.52999877929688,144.69000244140625,45153100
4,2024-01-08,149.10000610351562,149.39999389648438,146.14999389648438,146.74000549316406,46757100

In [ ]:
df_az=df_az.rename(columns={"Price":"Date"})

In [ ]:
df_az.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    502 non-null    datetime64[ns]
 1   Close   502 non-null    float64
 2   High    502 non-null    float64
 3   Low     502 non-null    float64
 4   Open    502 non-null    float64
 5   Volume  502 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 23.7 KB

In [ ]:
df_az["Date"]=pd.to_datetime(df_az["Date"])
df_az["Close"]=df_az.Close.astype("float")
df_az["High"]=df_az.High.astype("float")
df_az["Low"]=df_az.Low.astype("float")
df_az["Open"]=df_az.Open.astype("float")
df_az["Volume"]=df_az.Volume.astype("float")
df_az.tail(10)

          Date       Close        High         Low        Open      Volume
492 2025-12-17  221.270004  225.190002  220.990005  224.660004  44034400.0
493 2025-12-18  226.759995  229.229996  224.410004  225.710007  50272400.0
494 2025-12-19  227.350006  229.130005  225.580002  226.759995  85544400.0
495 2025-12-22  228.429993  229.479996  226.710007  228.610001  32261300.0
496 2025-12-23  232.139999  232.449997  228.729996  229.059998  29230200.0
497 2025-12-24  232.380005  232.949997  231.330002  232.130005  11420500.0
498 2025-12-26  232.520004  232.990005  231.179993  232.039993  15994700.0
499 2025-12-29  232.070007  232.600006  230.770004  231.940002  19797900.0
500 2025-12-30  232.529999  232.770004  230.199997  231.210007  21910500.0
501 2025-12-31  230.820007  232.990005  230.119995  232.910004  24383700.0

In [ ]:
df_az[(df_az.Open<200)]

          Date       Close        High         Low        Open      Volume
0   2024-01-02  149.929993  152.380005  148.389999  151.539993  47339400.0
1   2024-01-03  148.470001  151.050003  148.330002  149.199997  49425500.0
2   2024-01-04  144.570007  147.380005  144.050003  145.589996  56039800.0
3   2024-01-05  145.240005  146.589996  144.529999  144.690002  45153100.0
4   2024-01-08  149.100006  149.399994  146.149994  146.740005  46757100.0
..         ...         ...         ...         ...         ...         ...
336 2025-05-06  185.009995  187.929993  183.850006  184.570007  29314100.0
337 2025-05-07  188.710007  190.990005  185.009995  185.559998  43948600.0
338 2025-05-08  192.080002  194.330002  188.820007  191.429993  41043600.0
339 2025-05-09  193.059998  194.690002  191.160004  193.380005  29663100.0
349 2025-05-23  200.990005  202.369995  197.850006  198.899994  33393500.0

[255 rows x 6 columns]

In [ ]:
df_az.loc[df_az.Open<100,"status"]="Atipico"
df_az

,Date,Close,High,Low,Open,Volume,status
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN
...,...,...,...,...,...,...,...
497,2025-12-24,232.380005,232.949997,231.330002,232.130005,11420500.0,NaN
498,2025-12-26,232.520004,232.990005,231.179993,232.039993,15994700.0,NaN
499,2025-12-29,232.070007,232.600006,230.770004,231.940002,19797900.0,NaN
500,2025-12-30,232.529999,232.770004,230.199997,231.210007,21910500.0,NaN
501,2025-12-31,230.820007,232.990005,230.119995,232.910004,24383700.0,NaN

In [ ]:
df_az["Tendencia"]="Estable"
df_az.head()

,Date,Close,High,Low,Open,Volume,status,Tendencia
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Estable
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Estable
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Estable
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Estable

In [ ]:
df_az.head()

,Date,Close,High,Low,Open,Volume,Status,Tendencia
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Estable
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Estable
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Estable
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Estable

In [ ]:
df_az.loc[df_az.Close>df_az.Close.shift(1),"Tendencia"]="Sube"
df_az.head(10)

,Date,Close,High,Low,Open,Volume,Status,Tendencia
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Estable
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Estable
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube
5,2024-01-09,151.369995,151.710007,148.210007,148.330002,43812600.0,NaN,Sube
6,2024-01-10,153.729996,154.419998,151.880005,152.059998,44421800.0,NaN,Sube
7,2024-01-11,155.179993,157.169998,153.119995,155.039993,49072700.0,NaN,Sube
8,2024-01-12,154.619995,156.199997,154.009995,155.389999,40484200.0,NaN,Estable
9,2024-01-16,153.160004,154.990005,152.149994,153.529999,41384600.0,NaN,Estable

In [ ]:
df_az.loc[df_az.Close<df_az.Close.shift(1),"Tendencia"]="Baja"
df_az.head(10)

,Date,Close,High,Low,Open,Volume,Status,Tendencia
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Baja
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Baja
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube
5,2024-01-09,151.369995,151.710007,148.210007,148.330002,43812600.0,NaN,Sube
6,2024-01-10,153.729996,154.419998,151.880005,152.059998,44421800.0,NaN,Sube
7,2024-01-11,155.179993,157.169998,153.119995,155.039993,49072700.0,NaN,Sube
8,2024-01-12,154.619995,156.199997,154.009995,155.389999,40484200.0,NaN,Baja
9,2024-01-16,153.160004,154.990005,152.149994,153.529999,41384600.0,NaN,Baja

In [ ]:
df_az.head()

,Date,Close,High,Low,Open,Volume,Status,Tendencia,Rango
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable,3.990005
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Baja,2.720001
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Baja,3.330002
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube,2.059998
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube,3.250000

In [ ]:
df_az.sort_values(by="Date",ascending=False).head()

,Date,Close,High,Low,Open,Volume,Status,Tendencia
501,2025-12-31,230.820007,232.990005,230.119995,232.910004,24383700.0,NaN,Baja
500,2025-12-30,232.529999,232.770004,230.199997,231.210007,21910500.0,NaN,Sube
499,2025-12-29,232.070007,232.600006,230.770004,231.940002,19797900.0,NaN,Baja
498,2025-12-26,232.520004,232.990005,231.179993,232.039993,15994700.0,NaN,Sube
497,2025-12-24,232.380005,232.949997,231.330002,232.130005,11420500.0,NaN,Sube

In [ ]:
df_az.sort_values(by="High",ascending=False)
df_az.head(10)

,Date,Close,High,Low,Open,Volume,Status,Tendencia
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Baja
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Baja
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube
5,2024-01-09,151.369995,151.710007,148.210007,148.330002,43812600.0,NaN,Sube
6,2024-01-10,153.729996,154.419998,151.880005,152.059998,44421800.0,NaN,Sube
7,2024-01-11,155.179993,157.169998,153.119995,155.039993,49072700.0,NaN,Sube
8,2024-01-12,154.619995,156.199997,154.009995,155.389999,40484200.0,NaN,Baja
9,2024-01-16,153.160004,154.990005,152.149994,153.529999,41384600.0,NaN,Baja

In [ ]:
df_az.sort_values(by=["Tendencia","High"],ascending=[True,False])

,Date,Close,High,Low,Open,Volume,Status,Tendencia
462,2025-11-04,249.320007,257.010010,248.660004,250.380005,51546300.0,NaN,Baja
464,2025-11-06,243.039993,250.380005,242.169998,249.160004,46004200.0,NaN,Baja
468,2025-11-12,244.199997,250.369995,243.750000,250.240005,31190100.0,NaN,Baja
469,2025-11-13,237.580002,243.750000,236.500000,243.050003,41401700.0,NaN,Baja
269,2025-01-29,237.070007,240.389999,236.149994,239.020004,26091700.0,NaN,Baja
...,...,...,...,...,...,...,...,...
6,2024-01-10,153.729996,154.419998,151.880005,152.059998,44421800.0,NaN,Sube
11,2024-01-18,153.500000,153.779999,151.820007,152.770004,37850200.0,NaN,Sube
5,2024-01-09,151.369995,151.710007,148.210007,148.330002,43812600.0,NaN,Sube
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube

In [ ]:
df_az["Rango"]=df_az["High"]-df_az["Low"]
df_az.head(10)

,Date,Close,High,Low,Open,Volume,Status,Tendencia,Rango
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,NaN,Estable,3.990005
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,NaN,Baja,2.720001
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,NaN,Baja,3.330002
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,NaN,Sube,2.059998
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,NaN,Sube,3.250000
5,2024-01-09,151.369995,151.710007,148.210007,148.330002,43812600.0,NaN,Sube,3.500000
6,2024-01-10,153.729996,154.419998,151.880005,152.059998,44421800.0,NaN,Sube,2.539993
7,2024-01-11,155.179993,157.169998,153.119995,155.039993,49072700.0,NaN,Sube,4.050003
8,2024-01-12,154.619995,156.199997,154.009995,155.389999,40484200.0,NaN,Baja,2.190002
9,2024-01-16,153.160004,154.990005,152.149994,153.529999,41384600.0,NaN,Baja,2.840012

In [ ]:
df_az.Tendencia.unique()

array(['Estable', 'Baja', 'Sube'], dtype=object)

In [ ]:
df_az.Tendencia.nunique()

3

In [ ]:
import datetime as dt

In [ ]:
df_az["Year"]=df_az.Date.dt.year
df_az["Month"]=df_az.Date.dt.month
df_az["Day"]=df_az.Date.dt.day

In [ ]:
df_az.head(10)

,Price,Close,High,Low,Open,Volume,Rango,Year,Month,Day
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,24.169922,2025,12,26
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09,32.409668,2025,12,24
458,2025-10-29,6890.589844,6920.339844,6851.910156,6910.950195,6.280130e+09,68.429688,2025,10,29
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,31.450195,2025,12,29
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,19.779785,2025,12,30
457,2025-10-28,6890.890137,6911.299805,6870.729980,6897.740234,5.695930e+09,40.569824,2025,10,28
496,2025-12-23,6909.790039,6910.879883,6868.810059,6872.410156,3.820560e+09,42.069824,2025,12,23
488,2025-12-11,6901.000000,6903.459961,6833.450195,6861.299805,5.021060e+09,70.009766,2025,12,11
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,56.870117,2025,12,31
487,2025-12-10,6886.680176,6900.669922,6824.689941,6833.490234,5.526570e+09,75.979980,2025,12,10

In [ ]:
df_az=df_az.drop(columns=["Status"])

In [ ]:
col=["Year","Month","Day"]
df_az[col].head()

   Year  Month  Day
0  2024      1    2
1  2024      1    3
2  2024      1    4
3  2024      1    5
4  2024      1    8

In [ ]:
df_az.head()

,Date,Close,High,Low,Open,Volume,Tendencia,Rango,Year,Month,Day
0,2024-01-02,149.929993,152.380005,148.389999,151.539993,47339400.0,Estable,3.990005,2024,1,2
1,2024-01-03,148.470001,151.050003,148.330002,149.199997,49425500.0,Baja,2.720001,2024,1,3
2,2024-01-04,144.570007,147.380005,144.050003,145.589996,56039800.0,Baja,3.330002,2024,1,4
3,2024-01-05,145.240005,146.589996,144.529999,144.690002,45153100.0,Sube,2.059998,2024,1,5
4,2024-01-08,149.100006,149.399994,146.149994,146.740005,46757100.0,Sube,3.250000,2024,1,8

In [ ]:
df_gold=pd.read_csv("/content/drive/MyDrive/Data/finanzas_gold.csv")

In [ ]:
df_gold.dop

,Unnamed: 0,Date,Close,High,Low,Open,Volume
0,0,2024-01-02,2064.399902,2073.699951,2057.100098,2063.500000,61.0
1,1,2024-01-03,2034.199951,2044.000000,2034.199951,2034.199951,54.0
2,2,2024-01-04,2042.300049,2044.500000,2038.000000,2041.599976,88.0
3,3,2024-01-05,2042.400024,2048.100098,2042.400024,2044.500000,12.0
4,4,2024-01-08,2026.599976,2033.699951,2019.099976,2019.099976,10.0
...,...,...,...,...,...,...,...
499,499,2025-12-24,4480.600098,4503.399902,4468.399902,4500.700195,500.0
500,500,2025-12-26,4529.100098,4556.299805,4502.000000,4512.000000,263.0
501,501,2025-12-29,4325.100098,4379.000000,4325.100098,4371.500000,2044.0
502,502,2025-12-30,4370.100098,4403.600098,4338.000000,4346.399902,1837.0
503,503,2025-12-31,4325.600098,4363.799805,4285.000000,4333.500000,785.0

In [ ]:
df_az.merge(df_gold,how="inner",left_on=["Date"],right_on=["Date"],suffixes=("_amazon","_gold"))

ValueError: You are trying to merge on datetime64[ns] and object columns for key 'Date'. If you wish to proceed you should use pd.concat

In [ ]:
df_az.to_csv("/content/drive/MyDrive/Data/finanzas_gspc.csv")

In [ ]:
df_gold.to_csv("/content/drive/MyDrive/Data/finanzas_gold.csv")