<a href="https://colab.research.google.com/github/Alexis0104343/Analisis_de_datos_2026/blob/main/Analis_de_datos_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Librerias

In [ ]:
import yfinance as yf

In [ ]:
import re

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sea

In [ ]:
import numpy as np

In [ ]:
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
import datetime as dt

In [ ]:
from statsmodels.tsa.seasonal import seasonal_decompose

#Cargar Archivos

In [ ]:
df_raw=pd.read_csv("/content/drive/MyDrive/Data/Mexico.csv",encoding="cp1252")

#Guardar Archivos

In [ ]:
df_raw.to_csv("/content/drive/MyDrive/Data/Mexico.csv")

In [ ]:
df_wide.to_csv("/content/drive/MyDrive/Data/Mexico_wide.csv")

In [ ]:
df_long.to_csv("/content/drive/MyDrive/Data/Mexico_long.csv")

#Codigo

In [ ]:
df_raw.head(100)

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Mexico,MEX,"Population, total",SP.POP.TOTL,36724615,37890118,39129200,40424065,41772049,43174477,...,122251351,123400057,124573711,125762982,126799054,127648148,128613117,129739759,130861007,..
1,Mexico,MEX,Population growth (annual %),SP.POP.GROW,..,3.12431006208309,3.21786520378848,3.2556284602266,3.28021557071982,3.30220788165866,...,0.969124204799117,0.935239396499786,0.9466023549862,0.950144329831411,0.820454117563552,0.66740537533078,0.753116988604166,0.872178517508623,0.860515443690537,..
2,Mexico,MEX,Surface area (sq. km),AG.SRF.TOTL.K2,..,1964380,1964380,1964380,1964380,1964380,...,1964375,1964375,1964380,1964380,1960647.2,1960647.2,1959142.3,1957193.9,..,..
3,Mexico,MEX,Population density (people per sq. km of land ...,EN.POP.DNST,..,19.4913027598446,20.1287070140693,20.7948069651997,21.4882322076185,22.2096643432187,...,62.8881149206513,63.4790282671879,64.0827752771419,64.6945559299365,65.227528485815,65.664316469045,66.1607124668844,66.7402757272564,..,..
4,Mexico,MEX,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,..,..,..,..,..,..,...,43.2,..,41.9,..,43.9,..,36.3,..,29.6,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Mexico,MEX,Adjusted savings: natural resources depletion ...,NY.ADJ.DRES.GN.ZS,..,..,..,..,..,..,...,1.46421487617434,1.75591712454308,2.32181291691064,1.67641516968497,1.10590360336365,2.75699380152104,..,..,..,..
96,Mexico,MEX,Adjusted savings: net forest depletion (% of GNI),NY.ADJ.DFOR.GN.ZS,..,..,..,..,..,..,...,0,0,0,0,0,0,..,..,..,..
97,Mexico,MEX,Adjusted savings: net forest depletion (curren...,NY.ADJ.DFOR.CD,..,..,..,..,..,..,...,0,0,0,0,0,0,..,..,..,..
98,Mexico,MEX,Adjusted savings: net national savings (% of GNI),NY.ADJ.NNAT.GN.ZS,..,..,..,..,..,..,...,5.43248021951399,6.14465269334006,6.45466958088385,6.32669317105238,5.38634334464819,3.602384018874,..,..,..,..
99,Mexico,MEX,Adjusted savings: net national savings (curren...,NY.ADJ.NNAT.CD,..,..,..,..,..,..,...,57018397602.2128,69362257555.7438,76768544461.9718,77945609506.0846,56816339340.0492,44645259712.601,..,..,..,..

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521 entries, 0 to 1520
Data columns (total 70 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   1518 non-null   object
 1   Country Code   1516 non-null   object
 2   Series Name    1516 non-null   object
 3   Series Code    1516 non-null   object
 4   1960 [YR1960]  1516 non-null   object
 5   1961 [YR1961]  1516 non-null   object
 6   1962 [YR1962]  1516 non-null   object
 7   1963 [YR1963]  1516 non-null   object
 8   1964 [YR1964]  1516 non-null   object
 9   1965 [YR1965]  1516 non-null   object
 10  1966 [YR1966]  1516 non-null   object
 11  1967 [YR1967]  1516 non-null   object
 12  1968 [YR1968]  1516 non-null   object
 13  1969 [YR1969]  1516 non-null   object
 14  1970 [YR1970]  1516 non-null   object
 15  1971 [YR1971]  1516 non-null   object
 16  1972 [YR1972]  1516 non-null   object
 17  1973 [YR1973]  1516 non-null   object
 18  1974 [YR1974]  1516 non-null   object
 19  1975 [YR1975]  1516 non-null   object
 20  1976 [YR1976]  1516 non-null   object
 21  1977 [YR1977]  1516 non-null   object
 22  1978 [YR1978]  1516 non-null   object
 23  1979 [YR1979]  1516 non-null   object
 24  1980 [YR1980]  1516 non-null   object
 25  1981 [YR1981]  1516 non-null   object
 26  1982 [YR1982]  1516 non-null   object
 27  1983 [YR1983]  1516 non-null   object
 28  1984 [YR1984]  1516 non-null   object
 29  1985 [YR1985]  1516 non-null   object
 30  1986 [YR1986]  1516 non-null   object
 31  1987 [YR1987]  1516 non-null   object
 32  1988 [YR1988]  1516 non-null   object
 33  1989 [YR1989]  1516 non-null   object
 34  1990 [YR1990]  1516 non-null   object
 35  1991 [YR1991]  1516 non-null   object
 36  1992 [YR1992]  1516 non-null   object
 37  1993 [YR1993]  1516 non-null   object
 38  1994 [YR1994]  1516 non-null   object
 39  1995 [YR1995]  1516 non-null   object
 40  1996 [YR1996]  1516 non-null   object
 41  1997 [YR1997]  1516 non-null   object
 42  1998 [YR1998]  1516 non-null   object
 43  1999 [YR1999]  1516 non-null   object
 44  2000 [YR2000]  1516 non-null   object
 45  2001 [YR2001]  1516 non-null   object
 46  2002 [YR2002]  1516 non-null   object
 47  2003 [YR2003]  1516 non-null   object
 48  2004 [YR2004]  1516 non-null   object
 49  2005 [YR2005]  1516 non-null   object
 50  2006 [YR2006]  1516 non-null   object
 51  2007 [YR2007]  1516 non-null   object
 52  2008 [YR2008]  1516 non-null   object
 53  2009 [YR2009]  1516 non-null   object
 54  2010 [YR2010]  1516 non-null   object
 55  2011 [YR2011]  1516 non-null   object
 56  2012 [YR2012]  1516 non-null   object
 57  2013 [YR2013]  1516 non-null   object
 58  2014 [YR2014]  1516 non-null   object
 59  2015 [YR2015]  1516 non-null   object
 60  2016 [YR2016]  1516 non-null   object
 61  2017 [YR2017]  1516 non-null   object
 62  2018 [YR2018]  1516 non-null   object
 63  2019 [YR2019]  1516 non-null   object
 64  2020 [YR2020]  1516 non-null   object
 65  2021 [YR2021]  1516 non-null   object
 66  2022 [YR2022]  1516 non-null   object
 67  2023 [YR2023]  1516 non-null   object
 68  2024 [YR2024]  1516 non-null   object
 69  2025 [YR2025]  1516 non-null   object
dtypes: object(70)
memory usage: 831.9+ KB

In [ ]:
df=df_raw.replace("..",np.nan)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521 entries, 0 to 1520
Data columns (total 70 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  1518 non-null   object
 1   Country Code  1516 non-null   object
 2   Series Name   1516 non-null   object
 3   Series Code   1516 non-null   object
 4   1960          240 non-null    float64
 5   1961          270 non-null    float64
 6   1962          283 non-null    float64
 7   1963          285 non-null    float64
 8   1964          285 non-null    float64
 9   1965          312 non-null    float64
 10  1966          316 non-null    float64
 11  1967          316 non-null    float64
 12  1968          314 non-null    float64
 13  1969          317 non-null    float64
 14  1970          428 non-null    float64
 15  1971          453 non-null    float64
 16  1972          478 non-null    float64
 17  1973          462 non-null    float64
 18  1974          480 non-null    float64
 19  1975          498 non-null    float64
 20  1976          500 non-null    float64
 21  1977          501 non-null    float64
 22  1978          507 non-null    float64
 23  1979          559 non-null    float64
 24  1980          603 non-null    float64
 25  1981          585 non-null    float64
 26  1982          590 non-null    float64
 27  1983          585 non-null    float64
 28  1984          609 non-null    float64
 29  1985          602 non-null    float64
 30  1986          604 non-null    float64
 31  1987          615 non-null    float64
 32  1988          617 non-null    float64
 33  1989          636 non-null    float64
 34  1990          754 non-null    float64
 35  1991          780 non-null    float64
 36  1992          792 non-null    float64
 37  1993          777 non-null    float64
 38  1994          807 non-null    float64
 39  1995          835 non-null    float64
 40  1996          889 non-null    float64
 41  1997          834 non-null    float64
 42  1998          904 non-null    float64
 43  1999          851 non-null    float64
 44  2000          1042 non-null   float64
 45  2001          914 non-null    float64
 46  2002          1039 non-null   float64
 47  2003          997 non-null    float64
 48  2004          1052 non-null   float64
 49  2005          1069 non-null   float64
 50  2006          1098 non-null   float64
 51  2007          1054 non-null   float64
 52  2008          1110 non-null   float64
 53  2009          1108 non-null   float64
 54  2010          1212 non-null   float64
 55  2011          1133 non-null   float64
 56  2012          1162 non-null   float64
 57  2013          1153 non-null   float64
 58  2014          1181 non-null   float64
 59  2015          1174 non-null   float64
 60  2016          1187 non-null   float64
 61  2017          1123 non-null   float64
 62  2018          1148 non-null   float64
 63  2019          1074 non-null   float64
 64  2020          1157 non-null   float64
 65  2021          1048 non-null   float64
 66  2022          1083 non-null   float64
 67  2023          949 non-null    float64
 68  2024          642 non-null    float64
 69  2025          84 non-null     float64
dtypes: float64(66), object(4)
memory usage: 831.9+ KB

In [ ]:
column_mapping={}
year_pattern=re.compile(r"(\d{4})\s*\[YR\d{4}\]")
for col in df.columns:
  match=year_pattern.match(col)
  if match:
    year=int(match.group(1))
    column_mapping[col]=year
  else:
    column_mapping[col]=col.strip()
df.rename(columns=column_mapping,inplace=True)
df.head()

,Country Name,Country Code,Series Name,Series Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Mexico,MEX,"Population, total",SP.POP.TOTL,36724615,37890118,39129200,40424065,41772049,43174477,...,122251351,123400057,124573711,125762982,126799054,127648148,128613117,129739759,130861007,NaN
1,Mexico,MEX,Population growth (annual %),SP.POP.GROW,NaN,3.12431006208309,3.21786520378848,3.2556284602266,3.28021557071982,3.30220788165866,...,0.969124204799117,0.935239396499786,0.9466023549862,0.950144329831411,0.820454117563552,0.66740537533078,0.753116988604166,0.872178517508623,0.860515443690537,NaN
2,Mexico,MEX,Surface area (sq. km),AG.SRF.TOTL.K2,NaN,1964380,1964380,1964380,1964380,1964380,...,1964375,1964375,1964380,1964380,1960647.2,1960647.2,1959142.3,1957193.9,NaN,NaN
3,Mexico,MEX,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,19.4913027598446,20.1287070140693,20.7948069651997,21.4882322076185,22.2096643432187,...,62.8881149206513,63.4790282671879,64.0827752771419,64.6945559299365,65.227528485815,65.664316469045,66.1607124668844,66.7402757272564,NaN,NaN
4,Mexico,MEX,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,43.2,NaN,41.9,NaN,43.9,NaN,36.3,NaN,29.6,NaN

In [ ]:
id_colums=["Country Name","Country Code","Series Name","Series Code"]

year_colums=[col for col in df.columns if isinstance(col,int)]

for year in year_colums:
  df[year]=pd.to_numeric(df[year],errors="coerce")
df.head()

,Country Name,Country Code,Series Name,Series Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Mexico,MEX,"Population, total",SP.POP.TOTL,36724615.0,3.789012e+07,3.912920e+07,4.042406e+07,4.177205e+07,4.317448e+07,...,1.222514e+08,1.234001e+08,1.245737e+08,1.257630e+08,1.267991e+08,1.276481e+08,1.286131e+08,1.297398e+08,1.308610e+08,NaN
1,Mexico,MEX,Population growth (annual %),SP.POP.GROW,NaN,3.124310e+00,3.217865e+00,3.255628e+00,3.280216e+00,3.302208e+00,...,9.691242e-01,9.352394e-01,9.466024e-01,9.501443e-01,8.204541e-01,6.674054e-01,7.531170e-01,8.721785e-01,8.605154e-01,NaN
2,Mexico,MEX,Surface area (sq. km),AG.SRF.TOTL.K2,NaN,1.964380e+06,1.964380e+06,1.964380e+06,1.964380e+06,1.964380e+06,...,1.964375e+06,1.964375e+06,1.964380e+06,1.964380e+06,1.960647e+06,1.960647e+06,1.959142e+06,1.957194e+06,NaN,NaN
3,Mexico,MEX,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,1.949130e+01,2.012871e+01,2.079481e+01,2.148823e+01,2.220966e+01,...,6.288811e+01,6.347903e+01,6.408278e+01,6.469456e+01,6.522753e+01,6.566432e+01,6.616071e+01,6.674028e+01,NaN,NaN
4,Mexico,MEX,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,4.320000e+01,NaN,4.190000e+01,NaN,4.390000e+01,NaN,3.630000e+01,NaN,2.960000e+01,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521 entries, 0 to 1520
Data columns (total 70 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  1518 non-null   object
 1   Country Code  1516 non-null   object
 2   Series Name   1516 non-null   object
 3   Series Code   1516 non-null   object
 4   1960          240 non-null    float64
 5   1961          270 non-null    float64
 6   1962          283 non-null    float64
 7   1963          285 non-null    float64
 8   1964          285 non-null    float64
 9   1965          312 non-null    float64
 10  1966          316 non-null    float64
 11  1967          316 non-null    float64
 12  1968          314 non-null    float64
 13  1969          317 non-null    float64
 14  1970          428 non-null    float64
 15  1971          453 non-null    float64
 16  1972          478 non-null    float64
 17  1973          462 non-null    float64
 18  1974          480 non-null    float64
 19  1975          498 non-null    float64
 20  1976          500 non-null    float64
 21  1977          501 non-null    float64
 22  1978          507 non-null    float64
 23  1979          559 non-null    float64
 24  1980          603 non-null    float64
 25  1981          585 non-null    float64
 26  1982          590 non-null    float64
 27  1983          585 non-null    float64
 28  1984          609 non-null    float64
 29  1985          602 non-null    float64
 30  1986          604 non-null    float64
 31  1987          615 non-null    float64
 32  1988          617 non-null    float64
 33  1989          636 non-null    float64
 34  1990          754 non-null    float64
 35  1991          780 non-null    float64
 36  1992          792 non-null    float64
 37  1993          777 non-null    float64
 38  1994          807 non-null    float64
 39  1995          835 non-null    float64
 40  1996          889 non-null    float64
 41  1997          834 non-null    float64
 42  1998          904 non-null    float64
 43  1999          851 non-null    float64
 44  2000          1042 non-null   float64
 45  2001          914 non-null    float64
 46  2002          1039 non-null   float64
 47  2003          997 non-null    float64
 48  2004          1052 non-null   float64
 49  2005          1069 non-null   float64
 50  2006          1098 non-null   float64
 51  2007          1054 non-null   float64
 52  2008          1110 non-null   float64
 53  2009          1108 non-null   float64
 54  2010          1212 non-null   float64
 55  2011          1133 non-null   float64
 56  2012          1162 non-null   float64
 57  2013          1153 non-null   float64
 58  2014          1181 non-null   float64
 59  2015          1174 non-null   float64
 60  2016          1187 non-null   float64
 61  2017          1123 non-null   float64
 62  2018          1148 non-null   float64
 63  2019          1074 non-null   float64
 64  2020          1157 non-null   float64
 65  2021          1048 non-null   float64
 66  2022          1083 non-null   float64
 67  2023          949 non-null    float64
 68  2024          642 non-null    float64
 69  2025          84 non-null     float64
dtypes: float64(66), object(4)
memory usage: 831.9+ KB

In [ ]:
df_long=pd.melt(df,id_vars=id_colums,value_vars=year_colums,var_name="Year",value_name="Value")
df_long["Year"]=df_long["Year"].astype(int)

In [ ]:
df_long.sort_values(by=["Series Name","Year"],inplace=True)
df_long.head()

,Country Name,Country Code,Series Name,Series Code,Year,Value
137,Mexico,MEX,ARI treatment (% of children under 5 taken to ...,SH.STA.ARIC.ZS,1960,NaN
1658,Mexico,MEX,ARI treatment (% of children under 5 taken to ...,SH.STA.ARIC.ZS,1961,NaN
3179,Mexico,MEX,ARI treatment (% of children under 5 taken to ...,SH.STA.ARIC.ZS,1962,NaN
4700,Mexico,MEX,ARI treatment (% of children under 5 taken to ...,SH.STA.ARIC.ZS,1963,NaN
6221,Mexico,MEX,ARI treatment (% of children under 5 taken to ...,SH.STA.ARIC.ZS,1964,NaN

In [ ]:
df_wide=df_long.pivot_table(index="Year",
                      columns="Series Name",
                      values="Value")
df_wide.head()

Series Name,ARI treatment (% of children under 5 taken to a health provider),Access to clean fuels and technologies for cooking (% of population),"Access to clean fuels and technologies for cooking, rural (% of rural population)","Access to clean fuels and technologies for cooking, urban (% of urban population)",Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)",...,"Wage and salaried workers, male (% of male employment) (modeled ILO estimate)","Wage and salaried workers, total (% of total employment) (modeled ILO estimate)",Wanted fertility rate (births per woman),"Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal)",Wholesale price index (2010 = 100),Women Business and the Law Index Score (scale 1-100),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),Young people (ages 15-24) newly infected with HIV
Year,,,,,,,,,,,,,,,,,,,,,
1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pio.tamplates.default="plotly_white"

In [ ]:
df_long["Series Name"].unique()

array(['ARI treatment (% of children under 5 taken to a health provider)',
       'Access to clean fuels and technologies for cooking (% of population)',
       'Access to clean fuels and technologies for cooking, rural (% of rural population)',
       ..., "Women's share of population ages 15+ living with HIV (%)",
       'Young people (ages 15-24) newly infected with HIV', nan],
      dtype=object)

In [ ]:
df_long["Series Name"].nunique()

1516

In [ ]:
indicador="GDP growth (annual %)"
series_indicador=df_long[df_long["Series Name"]==indicador][["Year","Value"]]
series_indicador.head()

      Year      Value
31    1960        NaN
1552  1961   5.000000
3073  1962   4.664415
4594  1963   8.106887
6115  1964  11.905481

In [ ]:
df_wide[indicador]

Year
1960          NaN
1961     5.000000
1962     4.664415
1963     8.106887
1964    11.905481
          ...
2021     6.048483
2022     3.709757
2023     3.353541
2024     1.427428
2025          NaN
Name: GDP growth (annual %), Length: 66, dtype: float64

In [ ]:
series_indicador.describe()

              Year      Value
count    66.000000  64.000000
mean   1992.500000   3.541608
std      19.196354   3.875642
min    1960.000000  -8.354035
25%    1976.250000   1.907344
50%    1992.500000   3.567027
75%    2008.750000   5.903315
max    2025.000000  11.905481

In [ ]:
indicadores_distribution=[
    "GDP growth (annual %)",
    "Inflation, GDP deflator (annual %)",
    "Poulation growth (annual %)",
    "Gross capital formation (% of GDP)"
]
df_subset=df_long[df_long["Series Name"].isin(indicadores_distribution)]
df_subset.head()

,Country Name,Country Code,Series Name,Series Code,Year,Value
31,Mexico,MEX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1960,NaN
1552,Mexico,MEX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1961,5.000000
3073,Mexico,MEX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1962,4.664415
4594,Mexico,MEX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1963,8.106887
6115,Mexico,MEX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1964,11.905481

In [ ]:
df_subset_dist.nunique()

NameError: name 'df_subset_dist' is not defined

In [ ]:
fig_hist=px.histogram(
    df_subset_dist,
    x="Value",
    color="Series Name",
    facet_col="Series Name",
    facet_col_wrap=2,
    marginal="box",
    title="Distribucionde indicadores economicos",
    labels=["Value":"Valor del indicador"],
    nbins=20
)
fig_hist.update_layout(showlegend=False)
fig_hist.update_yaxes(matches=None,showcticklabels=True)
fig_hist.update_xaxes(matches=None,showcticklabels=True)
gig_hist.for_each-annotation(lambda a: a.update(text=a.text))

In [ ]:
fig_hist.show()