<a href="https://colab.research.google.com/github/Alexis0104343/Analisis_de_datos_2026/blob/main/Dataframe_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [21]:
df_sp=pd.read_csv("/content/drive/MyDrive/Data/finanzas_gspc.csv")
df_sp.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,4742.830078125,4754.330078125,4722.669921875,4745.2001953125,3743050000
3,2024-01-03,4704.81005859375,4729.2900390625,4699.7099609375,4725.06982421875,3950760000
4,2024-01-04,4688.68017578125,4726.77978515625,4687.52978515625,4697.419921875,3715480000

In [22]:
df_sp.colums=["Date","Close","High","Low","Open","Volume"]
df_sp.head()

/tmp/ipython-input-2441327669.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_sp.colums=["Date","Close","High","Low","Open","Volume"]

,Price,Close,High,Low,Open,Volume
0,Ticker,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,4742.830078125,4754.330078125,4722.669921875,4745.2001953125,3743050000
3,2024-01-03,4704.81005859375,4729.2900390625,4699.7099609375,4725.06982421875,3950760000
4,2024-01-04,4688.68017578125,4726.77978515625,4687.52978515625,4697.419921875,3715480000

In [24]:
df_sp=df_sp.iloc[2:,:].reset_index(drop=True)

In [25]:
df_sp.head()

,Price,Close,High,Low,Open,Volume
0,2024-01-02,4742.830078125,4754.330078125,4722.669921875,4745.2001953125,3743050000
1,2024-01-03,4704.81005859375,4729.2900390625,4699.7099609375,4725.06982421875,3950760000
2,2024-01-04,4688.68017578125,4726.77978515625,4687.52978515625,4697.419921875,3715480000
3,2024-01-05,4697.240234375,4721.490234375,4682.10986328125,4690.56982421875,3844370000
4,2024-01-08,4763.5400390625,4764.5400390625,4699.81982421875,4703.7001953125,3742320000

In [29]:
df_sp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   502 non-null    datetime64[ns]
 1   Close   502 non-null    float64
 2   High    502 non-null    float64
 3   Low     502 non-null    float64
 4   Open    502 non-null    float64
 5   Volume  502 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 23.7 KB

In [28]:
df_sp["Price"]=pd.to_datetime(df_sp["Price"])
#df_sp["Price"]=df_sp.Price.astype("float")
df_sp["Close"]=df_sp.Close.astype("float")
df_sp["High"]=df_sp.High.astype("float")
df_sp["Low"]=df_sp.Low.astype("float")
df_sp["Open"]=df_sp.Open.astype("float")
df_sp["Volume"]=df_sp.Volume.astype("float")
df_sp.tail(10)

,Price,Close,High,Low,Open,Volume
492,2025-12-17,6721.430176,6812.259766,6720.430176,6802.879883,5.122120e+09
493,2025-12-18,6774.759766,6816.129883,6758.500000,6778.060059,5.101190e+09
494,2025-12-19,6834.500000,6840.020020,6792.620117,6792.620117,8.554470e+09
495,2025-12-22,6878.490234,6882.029785,6855.740234,6865.209961,4.465030e+09
496,2025-12-23,6909.790039,6910.879883,6868.810059,6872.410156,3.820560e+09
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09

In [ ]:
df_sp[(df;sp.Open<250)]

In [33]:
df_sp.loc[df_sp.Open<6800,"status"]="Atipico"
df_sp

,Price,Close,High,Low,Open,Volume,status
0,2024-01-02,4742.830078,4754.330078,4722.669922,4745.200195,3.743050e+09,Atipico
1,2024-01-03,4704.810059,4729.290039,4699.709961,4725.069824,3.950760e+09,Atipico
2,2024-01-04,4688.680176,4726.779785,4687.529785,4697.419922,3.715480e+09,Atipico
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico
...,...,...,...,...,...,...,...
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09,NaN
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,NaN
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,NaN
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,NaN
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,NaN

In [34]:
df_sp["Tendencia"]="Estable"
df_sp-head()

NameError: name 'head' is not defined

In [35]:
df_sp.head()

,Price,Close,High,Low,Open,Volume,status,Tendencia
0,2024-01-02,4742.830078,4754.330078,4722.669922,4745.200195,3.743050e+09,Atipico,Estable
1,2024-01-03,4704.810059,4729.290039,4699.709961,4725.069824,3.950760e+09,Atipico,Estable
2,2024-01-04,4688.680176,4726.779785,4687.529785,4697.419922,3.715480e+09,Atipico,Estable
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico,Estable
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico,Estable

In [36]:
df_sp.loc[df_sp.Close>df_sp.Close.shift(1),"Tendencia"]="Sube"
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,status,Tendencia
0,2024-01-02,4742.830078,4754.330078,4722.669922,4745.200195,3.743050e+09,Atipico,Estable
1,2024-01-03,4704.810059,4729.290039,4699.709961,4725.069824,3.950760e+09,Atipico,Estable
2,2024-01-04,4688.680176,4726.779785,4687.529785,4697.419922,3.715480e+09,Atipico,Estable
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico,Sube
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico,Sube
5,2024-01-09,4756.500000,4765.470215,4730.350098,4741.930176,3.529960e+09,Atipico,Estable
6,2024-01-10,4783.450195,4790.799805,4756.200195,4759.939941,3.498680e+09,Atipico,Sube
7,2024-01-11,4780.240234,4798.500000,4739.580078,4792.129883,3.759890e+09,Atipico,Estable
8,2024-01-12,4783.830078,4802.399902,4768.979980,4791.180176,3.486340e+09,Atipico,Sube
9,2024-01-16,4765.979980,4782.339844,4747.120117,4772.350098,4.260550e+09,Atipico,Estable

In [37]:
df_sp.loc[df_sp.Close<df_sp.Close.shift(1),"Tendencia"]="Baja"
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,status,Tendencia
0,2024-01-02,4742.830078,4754.330078,4722.669922,4745.200195,3.743050e+09,Atipico,Estable
1,2024-01-03,4704.810059,4729.290039,4699.709961,4725.069824,3.950760e+09,Atipico,Baja
2,2024-01-04,4688.680176,4726.779785,4687.529785,4697.419922,3.715480e+09,Atipico,Baja
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico,Sube
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico,Sube
5,2024-01-09,4756.500000,4765.470215,4730.350098,4741.930176,3.529960e+09,Atipico,Baja
6,2024-01-10,4783.450195,4790.799805,4756.200195,4759.939941,3.498680e+09,Atipico,Sube
7,2024-01-11,4780.240234,4798.500000,4739.580078,4792.129883,3.759890e+09,Atipico,Baja
8,2024-01-12,4783.830078,4802.399902,4768.979980,4791.180176,3.486340e+09,Atipico,Sube
9,2024-01-16,4765.979980,4782.339844,4747.120117,4772.350098,4.260550e+09,Atipico,Baja

In [38]:
df_sp=df_sp.sort_values(by="Price")
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,status,Tendencia
0,2024-01-02,4742.830078,4754.330078,4722.669922,4745.200195,3.743050e+09,Atipico,Estable
1,2024-01-03,4704.810059,4729.290039,4699.709961,4725.069824,3.950760e+09,Atipico,Baja
2,2024-01-04,4688.680176,4726.779785,4687.529785,4697.419922,3.715480e+09,Atipico,Baja
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico,Sube
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico,Sube
5,2024-01-09,4756.500000,4765.470215,4730.350098,4741.930176,3.529960e+09,Atipico,Baja
6,2024-01-10,4783.450195,4790.799805,4756.200195,4759.939941,3.498680e+09,Atipico,Sube
7,2024-01-11,4780.240234,4798.500000,4739.580078,4792.129883,3.759890e+09,Atipico,Baja
8,2024-01-12,4783.830078,4802.399902,4768.979980,4791.180176,3.486340e+09,Atipico,Sube
9,2024-01-16,4765.979980,4782.339844,4747.120117,4772.350098,4.260550e+09,Atipico,Baja

In [39]:
df_sp=df_sp.sort_values(by="High",ascending=False)
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,status,Tendencia
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,NaN,Baja
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09,NaN,Sube
458,2025-10-29,6890.589844,6920.339844,6851.910156,6910.950195,6.280130e+09,NaN,Baja
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,NaN,Baja
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,NaN,Baja
457,2025-10-28,6890.890137,6911.299805,6870.729980,6897.740234,5.695930e+09,NaN,Sube
496,2025-12-23,6909.790039,6910.879883,6868.810059,6872.410156,3.820560e+09,NaN,Sube
488,2025-12-11,6901.000000,6903.459961,6833.450195,6861.299805,5.021060e+09,NaN,Sube
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,NaN,Baja
487,2025-12-10,6886.680176,6900.669922,6824.689941,6833.490234,5.526570e+09,NaN,Sube

In [46]:
df_sp.sort_values(by=["Tendencia","High"],ascending=[True,False])

,Price,Close,High,Low,Open,Volume,status,Tendencia,Rango
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,NaN,Baja,24.169922
458,2025-10-29,6890.589844,6920.339844,6851.910156,6910.950195,6.280130e+09,NaN,Baja,68.429688
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,NaN,Baja,31.450195
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,NaN,Baja,19.779785
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,NaN,Baja,56.870117
...,...,...,...,...,...,...,...,...,...
8,2024-01-12,4783.830078,4802.399902,4768.979980,4791.180176,3.486340e+09,Atipico,Sube,33.419922
6,2024-01-10,4783.450195,4790.799805,4756.200195,4759.939941,3.498680e+09,Atipico,Sube,34.599609
11,2024-01-18,4780.939941,4785.790039,4740.569824,4760.100098,4.019000e+09,Atipico,Sube,45.220215
4,2024-01-08,4763.540039,4764.540039,4699.819824,4703.700195,3.742320e+09,Atipico,Sube,64.720215
3,2024-01-05,4697.240234,4721.490234,4682.109863,4690.569824,3.844370e+09,Atipico,Sube,39.380371

In [42]:
df_sp["Rango"]=df_sp["High"]-df_sp["Low"]
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,status,Tendencia,Rango
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,NaN,Baja,24.169922
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09,NaN,Sube,32.409668
458,2025-10-29,6890.589844,6920.339844,6851.910156,6910.950195,6.280130e+09,NaN,Baja,68.429688
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,NaN,Baja,31.450195
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,NaN,Baja,19.779785
457,2025-10-28,6890.890137,6911.299805,6870.729980,6897.740234,5.695930e+09,NaN,Sube,40.569824
496,2025-12-23,6909.790039,6910.879883,6868.810059,6872.410156,3.820560e+09,NaN,Sube,42.069824
488,2025-12-11,6901.000000,6903.459961,6833.450195,6861.299805,5.021060e+09,NaN,Sube,70.009766
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,NaN,Baja,56.870117
487,2025-12-10,6886.680176,6900.669922,6824.689941,6833.490234,5.526570e+09,NaN,Sube,75.979980

In [43]:
df_sp.Tendencia.unique()

array(['Baja', 'Sube', 'Estable'], dtype=object)

In [45]:
df_sp.Tendencia.nunique()

3

In [47]:
import datetime as dt

In [49]:
df_sp["Year"]=df_sp.Price.dt.year
df_sp["Month"]=df_sp.Price.dt.month
df_sp["Day"]=df_sp.Price.dt.day

In [55]:
df_sp.head(10)

,Price,Close,High,Low,Open,Volume,Rango,Year,Month,Day
498,2025-12-26,6929.939941,6945.770020,6921.600098,6936.020020,2.586550e+09,24.169922,2025,12,26
497,2025-12-24,6932.049805,6937.319824,6904.910156,6904.910156,1.798270e+09,32.409668,2025,12,24
458,2025-10-29,6890.589844,6920.339844,6851.910156,6910.950195,6.280130e+09,68.429688,2025,10,29
499,2025-12-29,6905.740234,6920.209961,6888.759766,6903.600098,3.541750e+09,31.450195,2025,12,29
500,2025-12-30,6896.240234,6913.250000,6893.470215,6900.439941,3.309930e+09,19.779785,2025,12,30
457,2025-10-28,6890.890137,6911.299805,6870.729980,6897.740234,5.695930e+09,40.569824,2025,10,28
496,2025-12-23,6909.790039,6910.879883,6868.810059,6872.410156,3.820560e+09,42.069824,2025,12,23
488,2025-12-11,6901.000000,6903.459961,6833.450195,6861.299805,5.021060e+09,70.009766,2025,12,11
501,2025-12-31,6845.500000,6901.419922,6844.549805,6898.819824,3.261830e+09,56.870117,2025,12,31
487,2025-12-10,6886.680176,6900.669922,6824.689941,6833.490234,5.526570e+09,75.979980,2025,12,10

In [54]:
df_sp=df_sp.drop(columns=["status"])

In [56]:
col=["Year","Month","Day"]
df_sp[col].head()

     Year  Month  Day
498  2025     12   26
497  2025     12   24
458  2025     10   29
499  2025     12   29
500  2025     12   30

In [68]:
import yfinance as yf
df_gold=yf.download("GC=F",start="2024-01-01",end="2026-01-01")
df_gold.head()

/tmp/ipython-input-4210527928.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_gold=yf.download("GC=F",start="2024-01-01",end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open Volume
Ticker             GC=F         GC=F         GC=F         GC=F   GC=F
Date
2024-01-02  2064.399902  2073.699951  2057.100098  2063.500000     61
2024-01-03  2034.199951  2044.000000  2034.199951  2034.199951     54
2024-01-04  2042.300049  2044.500000  2038.000000  2041.599976     88
2024-01-05  2042.400024  2048.100098  2042.400024  2044.500000     12
2024-01-08  2026.599976  2033.699951  2019.099976  2019.099976     10

In [70]:

df_gold.colums=["Date","lose","High","Low","Open","Volume"]
df_gold.head()

/tmp/ipython-input-3504628315.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_gold.colums=["Date","lose","High","Low","Open","Volume"]

Price         Close         High          Low         Open Volume
Ticker         GC=F         GC=F         GC=F         GC=F   GC=F
0       2042.300049  2044.500000  2038.000000  2041.599976     88
1       2042.400024  2048.100098  2042.400024  2044.500000     12
2       2026.599976  2033.699951  2019.099976  2019.099976     10
3       2026.400024  2035.800049  2026.400024  2035.800049     27
4       2021.699951  2035.599976  2021.699951  2029.000000    538

In [69]:
df_gold=df_gold.iloc[2:,:].reset_index(drop=True)

In [74]:
df_sp.merge(df_gold,how="inner",left_on=["Price"],right_on=["Date"],suffixes=("_sp500","_gold"))

MergeError: Not allowed to merge between different levels. (1 levels on the left, 2 on the right)

In [75]:
df_sp.to_csv("/content/drive/MyDrive/Data/finanzas_gspc.csv")

In [76]:
df_gold.to_csv("/content/drive/MyDrive/Data/finanzas_gold.csv")